// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package testproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetProxyRequest struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProxyRequest) Reset()         { *m = GetProxyRequest{} }
func (m *GetProxyRequest) String() string { return proto.CompactTextString(m) }
func (*GetProxyRequest) ProtoMessage()    {}
func (*GetProxyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *GetProxyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProxyRequest.Unmarshal(m, b)
}
func (m *GetProxyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProxyRequest.Marshal(b, m, deterministic)
}
func (m *GetProxyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProxyRequest.Merge(m, src)
}
func (m *GetProxyRequest) XXX_Size() int {
	return xxx_messageInfo_GetProxyRequest.Size(m)
}
func (m *GetProxyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProxyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProxyRequest proto.InternalMessageInfo

func (m *GetProxyRequest) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetProxyResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProxyResponse) Reset()         { *m = GetProxyResponse{} }
func (m *GetProxyResponse) String() string { return proto.CompactTextString(m) }
func (*GetProxyResponse) ProtoMessage()    {}
func (*GetProxyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *GetProxyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProxyResponse.Unmarshal(m, b)
}
func (m *GetProxyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProxyResponse.Marshal(b, m, deterministic)
}
func (m *GetProxyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProxyResponse.Merge(m, src)
}
func (m *GetProxyResponse) XXX_Size() int {
	return xxx_messageInfo_GetProxyResponse.Size(m)
}
func (m *GetProxyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProxyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProxyResponse proto.InternalMessageInfo

func (m *GetProxyResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateAccountRequest struct {
	AccountId            int32    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CountryCode          string   `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountId() int32 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *CreateAccountRequest) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *CreateAccountRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateAccountResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*GetProxyRequest)(nil), "proxyPb.GetProxyRequest")
	proto.RegisterType((*GetProxyResponse)(nil), "proxyPb.GetProxyResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "proxyPb.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "proxyPb.CreateAccountResponse")
}

func init() {
	proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf)
}

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x28, 0xca, 0xaf,
	0xa8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x07, 0x73, 0x02, 0x92, 0x94, 0x0c, 0xb8,
	0xf8, 0xdd, 0x53, 0x4b, 0x02, 0x40, 0xbc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x59,
	0x2e, 0xae, 0xc4, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc, 0x92, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46,
	0x0d, 0xd6, 0x20, 0x4e, 0xa8, 0x88, 0x67, 0x8a, 0x92, 0x0a, 0x97, 0x00, 0x42, 0x47, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x69, 0x51, 0x0e, 0x58, 0x2d, 0x67, 0x10, 0x88,
	0xa9, 0x94, 0xc9, 0x25, 0xe2, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0xea, 0x08, 0xd1, 0x08, 0x33, 0x5c,
	0x86, 0x0b, 0x61, 0x14, 0x86, 0xd9, 0x42, 0x8a, 0x5c, 0x3c, 0x60, 0x66, 0x51, 0x65, 0x7c, 0x72,
	0x7e, 0x4a, 0xaa, 0x04, 0x13, 0xd8, 0x40, 0x6e, 0xa8, 0x98, 0x73, 0x7e, 0x0a, 0xdc, 0x2a, 0x66,
	0x84, 0x55, 0x9a, 0x5c, 0xa2, 0x68, 0x56, 0xe1, 0x72, 0x95, 0xd1, 0x62, 0x46, 0x2e, 0x1e, 0xb0,
	0xcb, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x02, 0xb8, 0x78, 0x51, 0xf4, 0x0a, 0xc9,
	0xea, 0x41, 0x43, 0x46, 0x0f, 0x9b, 0xf3, 0xa5, 0xe4, 0x70, 0x49, 0x43, 0xac, 0x54, 0x62, 0x10,
	0x72, 0xe4, 0xe2, 0x80, 0x05, 0x8f, 0x90, 0x04, 0x5c, 0x35, 0x5a, 0x18, 0x4b, 0x49, 0x62, 0x91,
	0x81, 0x19, 0xe1, 0xc4, 0x1d, 0xc5, 0x59, 0x92, 0x5a, 0x5c, 0x02, 0x8e, 0xa9, 0x24, 0x36, 0x30,
	0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xba, 0x29, 0xd0, 0xac, 0xbf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyServiceClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	GetProxy(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*GetProxyResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/proxyPb.ProxyService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyServiceClient) GetProxy(ctx context.Context, in *GetProxyRequest, opts ...grpc.CallOption) (*GetProxyResponse, error) {
	out := new(GetProxyResponse)
	err := c.cc.Invoke(ctx, "/proxyPb.ProxyService/GetProxy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
type ProxyServiceServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	GetProxy(context.Context, *GetProxyRequest) (*GetProxyResponse, error)
}

// UnimplementedProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProxyServiceServer struct {
}

func (*UnimplementedProxyServiceServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedProxyServiceServer) GetProxy(ctx context.Context, req *GetProxyRequest) (*GetProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProxy not implemented")
}

func RegisterProxyServiceServer(s *grpc.Server, srv ProxyServiceServer) {
	s.RegisterService(&_ProxyService_serviceDesc, srv)
}

func _ProxyService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxyPb.ProxyService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyService_GetProxy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).GetProxy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proxyPb.ProxyService/GetProxy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).GetProxy(ctx, req.(*GetProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proxyPb.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _ProxyService_CreateAccount_Handler,
		},
		{
			MethodName: "GetProxy",
			Handler:    _ProxyService_GetProxy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proxy.proto",
}
